"""add_block_id_to_transactions

Revision ID: 48e304bbcece
Revises: aa55c34dacf4
Create Date: 2026-01-11 07:30:55.131160+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48e304bbcece"
down_revision: str | None = "aa55c34dacf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("block_id", sa.Integer(), nullable=True))
    op.create_index("ix_transactions_block_id", "transactions", ["block_id"], unique=False)
    op.create_foreign_key(None, "transactions", "blocks", ["block_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_index("ix_transactions_block_id", table_name="transactions")
    op.drop_column("transactions", "block_id")
    # ### end Alembic commands ###
