"""create_core_schema_and_migrate_leads

Revision ID: 5cb8c456550e
Revises:
Create Date: 2026-01-10 07:26:45.295960+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cb8c456550e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block", sa.String(length=50), nullable=False),
        sa.Column("street", sa.String(length=255), nullable=False),
        sa.Column("town", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("lease_commence_year", sa.Integer(), nullable=True),
        sa.Column("flat_mix_distribution", sa.JSON(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="check_block_latitude_range"),
        sa.CheckConstraint("lease_commence_year >= 1960", name="check_lease_commence_year_valid"),
        sa.CheckConstraint(
            "longitude >= -180 AND longitude <= 180", name="check_block_longitude_range"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("block", "street", name="uq_block_street"),
    )
    op.create_index("ix_blocks_block_street", "blocks", ["block", "street"], unique=False)
    op.create_index("ix_blocks_town", "blocks", ["town"], unique=False)
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_name", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "SUCCESS", "FAILED", name="ingestionstatus"),
            nullable=False,
        ),
        sa.Column("rows_processed", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint("rows_processed >= 0", name="check_rows_processed_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_runs_dataset_started",
        "ingestion_runs",
        ["dataset_name", "started_at"],
        unique=False,
    )
    op.create_index("ix_ingestion_runs_status", "ingestion_runs", ["status"], unique=False)
    op.create_table(
        "leads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("mobile", sa.String(length=20), nullable=False),
        sa.Column("contact_window", sa.String(length=100), nullable=True),
        sa.Column("budget_range", sa.String(length=100), nullable=True),
        sa.Column("preferred_towns", sa.JSON(), nullable=False),
        sa.Column("flat_types", sa.JSON(), nullable=False),
        sa.Column("timeline", sa.String(length=100), nullable=True),
        sa.Column("first_timer", sa.Boolean(), nullable=False),
        sa.Column("financing_status", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("filter_snapshot", sa.JSON(), nullable=True),
        sa.Column("shortlist_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.Enum("NEW", "CONTACTED", "CLOSED", name="leadstatus"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_leads_created_status", "leads", ["created_at", "status"], unique=False)
    op.create_index(op.f("ix_leads_id"), "leads", ["id"], unique=False)
    op.create_index("ix_leads_status", "leads", ["status"], unique=False)
    op.create_table(
        "pois",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "poi_type",
            sa.Enum(
                "MRT",
                "LRT",
                "SUPERMARKET",
                "CLINIC",
                "PARK",
                "MALL",
                "HAWKER",
                "SCHOOL",
                name="poitype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="check_poi_latitude_range"),
        sa.CheckConstraint(
            "longitude >= -180 AND longitude <= 180", name="check_poi_longitude_range"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pois_type_lat_lng", "pois", ["poi_type", "latitude", "longitude"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("block", sa.String(length=50), nullable=False),
        sa.Column("street", sa.String(length=255), nullable=False),
        sa.Column("flat_type", sa.String(length=50), nullable=False),
        sa.Column("storey_range", sa.String(length=50), nullable=False),
        sa.Column("floor_area_sqm", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("lease_commence_date", sa.Integer(), nullable=False),
        sa.Column("town", sa.String(length=100), nullable=False),
        sa.Column("flat_model", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("floor_area_sqm > 0", name="check_floor_area_positive"),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="check_latitude_range"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180", name="check_longitude_range"),
        sa.CheckConstraint("price > 0", name="check_price_positive"),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "block",
            "street",
            "flat_type",
            "date",
            "storey_range",
            "floor_area_sqm",
            name="uq_transaction_details",
        ),
    )
    op.create_index(
        "ix_transactions_block_street_flat_type_date",
        "transactions",
        ["block", "street", "flat_type", "date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_lat_lng", "transactions", ["latitude", "longitude"], unique=False
    )
    op.create_index(
        "ix_transactions_town_flat_type_date",
        "transactions",
        ["town", "flat_type", "date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_town_flat_type_date", table_name="transactions")
    op.drop_index("ix_transactions_lat_lng", table_name="transactions")
    op.drop_index("ix_transactions_block_street_flat_type_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_pois_type_lat_lng", table_name="pois")
    op.drop_table("pois")
    op.drop_index("ix_leads_status", table_name="leads")
    op.drop_index(op.f("ix_leads_id"), table_name="leads")
    op.drop_index("ix_leads_created_status", table_name="leads")
    op.drop_table("leads")
    op.drop_index("ix_ingestion_runs_status", table_name="ingestion_runs")
    op.drop_index("ix_ingestion_runs_dataset_started", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index("ix_blocks_town", table_name="blocks")
    op.drop_index("ix_blocks_block_street", table_name="blocks")
    op.drop_table("blocks")
    # ### end Alembic commands ###
